# Generated by Django 3.2.6 on 2021-08-28 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('profile_img', models.ImageField(upload_to='photos/realtors/%Y/%m/%d/')),
                ('is_mvp', models.BooleanField(default=True)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
