# Generated by Django 3.2.6 on 2021-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='profile_img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
